/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SI_gui;
import gpt.*;
//import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jempol
 */
public class TransaksiSekolahKepsek extends javax.swing.JFrame 
{
    public Connection con;
    ArrayList skulAll = new ArrayList();
    ArrayList kepAll = new ArrayList();
    int idkepsek;
    
    public void koneksi()throws SQLException, ClassNotFoundException{
       try{
            String url , timezone, user, pass;
            url = "jdbc:mysql://localhost/si_sekolah";
            timezone = "?usetimezone=true&serverTimezone=UTC";
            user = "root";
            pass = "";
            con = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url+timezone, user, pass);
          }

       catch(ClassNotFoundException ex){
            Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    private void tampil_combo() {
    try{
        koneksi();
        String query = "select Nama_Sekolah from sekolah";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        
        cb_sekolah.addItem("pilih sekolah");
        cb_kepsek.addItem("pilih kepala sekolah");
        
        while (rs.next()){
            String temp = rs.getString("Nama_Sekolah");
            cb_sekolah.addItem(temp);
            skulAll.add(temp);
        }
        
        query = "select Nama_Kepsek from Kepala_Sekolah where Nama_Kepsek != 'default'";
        rs = st.executeQuery(query);
        while (rs.next()){
            String temp = rs.getString("Nama_Kepsek");
            cb_kepsek.addItem(temp);
            kepAll.add(temp);
        }
        
        
    }catch (Exception ex) {
            Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void insertDb() throws Exception{
       try{
                String query2 = "select * from kepala_sekolah WHERE Nama_Kepsek = (?)";
                Statement statement2 = con.createStatement();
                ResultSet rs = statement2.executeQuery(query2);

                Kepala_Sekolah kepsek = new Kepala_Sekolah();

                if (rs.next()){
                    kepsek.setId_Kepsek(rs.getInt("Id_Kepsek"));
                    kepsek.setNama_Kepsek(rs.getString("Nama_Kepsek"));
                }

                String query = "UPDATE sekolah SET Id_Kepsek = " + kepsek.getId_Kepsek() + " WHERE Nama_Sekolah = " + cb_sekolah.getSelectedItem();
                Statement statement = con.createStatement();
                rs = statement.executeQuery(query);
            }
       catch(Exception e){
           
       }
   }
    
    public TransaksiSekolahKepsek(){
        initComponents();
        tampil_combo();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_kepsek = new javax.swing.JComboBox<>();
        cb_sekolah = new javax.swing.JComboBox<>();
        btn_enter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        close1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA TRANSAKSI SEKOLAH --> KEPALA SEKOLAH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 601, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Sekolah");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 94, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Nama Kepala Sekolah");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 109, 157, 19);

        cb_kepsek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kepsekActionPerformed(evt);
            }
        });
        getContentPane().add(cb_kepsek);
        cb_kepsek.setBounds(214, 106, 265, 22);

        cb_sekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sekolahActionPerformed(evt);
            }
        });
        getContentPane().add(cb_sekolah);
        cb_sekolah.setBounds(214, 66, 265, 22);

        btn_enter.setText("ENTER");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enter);
        btn_enter.setBounds(214, 146, 70, 23);

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sekolah", "Nama Kepala Sekolah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_transaksi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 187, 693, 217);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        close1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 51, 51));
        close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close1.setText("X");
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(654, 0, 49, 46);

        setSize(new java.awt.Dimension(695, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_sekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sekolahActionPerformed
       
    }//GEN-LAST:event_cb_sekolahActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        
        try {                                          
            String query2 = "select * from kepala_sekolah WHERE Nama_Kepsek = (?)";
            PreparedStatement statement2 = SQL_SI.getConnection().prepareStatement(query2);
            statement2.setString(1, (String) cb_kepsek.getSelectedItem());
            ResultSet rs = statement2.executeQuery();

            Kepala_Sekolah kepsek = new Kepala_Sekolah();

            if (rs.next()){
                kepsek.setId_Kepsek(rs.getInt("Id_Kepsek"));
                kepsek.setNama_Kepsek(rs.getString("Nama_Kepsek"));
            }
            statement2.execute();
            statement2.close();
            
            String query = "UPDATE sekolah SET Id_Kepsek = (?) WHERE Nama_Sekolah = (?)";
            PreparedStatement statement = SQL_SI.getConnection().prepareStatement(query);
            statement.setInt(1, kepsek.getId_Kepsek());
            statement.setString(2, (String) cb_sekolah.getSelectedItem());
            
            statement.execute();
            statement.close();
            
            DefaultTableModel modelTable = (DefaultTableModel) tbl_transaksi.getModel();

            if ((cb_sekolah.getSelectedItem() == "pilih sekolah") && (cb_kepsek.getSelectedItem() == "pilih kepala sekolah")) 
                {
                    JOptionPane.showMessageDialog(null, "input data");
                }
            else   
            {
                query = "select sekolah.Nama_Sekolah, kepala_sekolah.Nama_Kepsek from kepala_sekolah, sekolah "
                        + "where sekolah.Id_Kepsek = kepala_sekolah.Id_Kepsek AND sekolah.Id_Kepsek != 0";
                 statement = SQL_SI.getConnection().prepareStatement(query);
                 rs = statement.executeQuery();

                 for (int i = modelTable.getRowCount() - 1; i > -1; i--) 
                    {
                        modelTable.removeRow(i);
                    }
                 
                 while(rs.next())
                 {
                     Object[] view = new Object[2];
                     view[0] = rs.getString("Nama_Sekolah");
                     view[1] = rs.getString("Nama_Kepsek");
                     modelTable.addRow(view);
                 }

                 statement.close();
                 rs.close();
                 tbl_transaksi.setModel(modelTable);
            }
       
            cb_sekolah.setSelectedIndex(0);
            cb_kepsek.setSelectedIndex(0);
        } catch (Exception ex) {
            Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_enterActionPerformed

    private void cb_kepsekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kepsekActionPerformed
       
    }//GEN-LAST:event_cb_kepsekActionPerformed

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiSekolahKepsek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiSekolahKepsek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter;
    private javax.swing.JComboBox<String> cb_kepsek;
    private javax.swing.JComboBox<String> cb_sekolah;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_transaksi;
    // End of variables declaration//GEN-END:variables
}
